### ISSUE TITLE
The Display isn't running

### ISSUE THREAD

**Issue by JavasPichu** [TheThinMatrix/OpenGL-Tutorial-2#2]
Receiving this error -
Exception in thread "main" java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL30.glGenVertexArrays(GL30.java:1550)
	at renderEngine.Loader.createVAO(Loader.java:35)
	at renderEngine.Loader.loadToVAO(Loader.java:19)
	at testingEngine.GameLoop.main(GameLoop.java:30)

-------------------------------------------

**Comment by ThePigStupo** [comment]
I get that too, weird
